### ISSUE TITLE
Feature request: Find price of coin on certain date

### ISSUE THREAD

**Issue by laboon** [codingholt/CoinGecko-CLI#1]
For example:

```
cg btc 01.09.2022
```

would show the price of Bitcoin on 1 September 2022

```
Price (1 September 2022):  20154           
```

Great tool, btw!

**Comment by codingholt** [comment]
@laboon thanks for your feature request.👍
In version 1.7.0 you can now type `cg date btc 01.09.2020`
and get the price on that date back like this `Bitcoin price (1 September 2020): 11672.32 $`

**Comment by laboon** [comment]
@codingholt Thanks, this is great! I sent some sats in appreciation. https://www.blockchain.com/btc/address/bc1q5jrx8aw5c4wq76rl0etxfhvv69gtnj7v3ldstc

**Comment by codingholt** [comment]
@laboon thank you very much! It wasn't necessary, but much appreciated. Glad you like it. 🙏
